name: iOS-CI

on:
  push:
    tags:
      - "appstore-*"

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Upload Flag to Server
        run: curl --location --request POST 'https://sandbox.coinhub.org/v1/version/block' --header 'Content-Type:application/json' --data-raw '{"build":${{ secrets.BUILD_NUM }}}'
