name: iOS-CI

on:
  push:
    tags:
      - "appstore-*"

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: CoolBank/wallet-ios
          token: ${{ secrets.MY_PAT }}
      
      - name: pod
        run: pod install --no-repo-update
        
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.P12_CER_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: build archive
        run: |
          xcodebuild -quiet -workspace Coinhub.xcworkspace -configuration Release  -scheme "Coinhub" -sdk iphoneos -destination generic/platform=iOS -archivePath $RUNNER_TEMP/coinhub.xcarchive PROVISIONING_PROFILE=aa0e578e-f99c-4a98-b1c8-a25b81fbe773 clean archive         

      - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/coinhub.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build          

      - name: Upload app to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/Coinhub.ipa
          
      - name: Upload app to TestFlight
        # You may pin to the exact commit or the version.
        # uses: Apple-Actions/upload-testflight-build@54dc215b4cd5529730db39f11c84efdb71414e07
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: $RUNNER_TEMP/build/Coinhub.ipa
          # The AppStoreConnect API Key Issuer Identifier
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          # The Key ID for AppStore Connect API
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          # The PKCS8 format Private Key for AppStore Connect API
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
